export const en = {
  data: {
    dashboard: {
      create_order: 'CREATE ORDER',
      pick_up: 'PICK UP ',
      create_order_desc: 'Would you like to send something today?',
      single_shipment: 'Single Shipment',
      bulk_shipment: 'Bulk Shipment',
      search_bar: 'Search by tracking no, name, email or phone no.',
      account_number: 'Account No',
      my_profile: 'My Profile',
      log_out: 'Log out',
      home: 'Home',
      x_order_pickup1: 'You have ',
      x_order_pickup2: 'order(s) ',
      x_order_pickup3: 'for pickup',
      request_pickup: 'Request for a Pick Up',
      my_orders: 'My Orders',
      select_date: 'Select Date Range',
      start_date: 'Start Date',
      end_date: 'End Date',
      my_shipment: 'My Shipment',
      pending_pickup: 'Pending Pick Up',
      live_shipments: 'Live Shipments',
      delivered: 'Delivered',
      failed_deliveries: 'Failed Deliveries',
      returns: 'Returns',
      my_cod: 'My COD Orders',
      see_orders: 'See Orders',
      collected: 'Collected From Recipient',
      pending_collection: 'Pending Collection',
      failed_collect: 'Failed to Collect',
      news_promo: 'NEWS AND PROMOS',
      insights: {
        performance_insights: 'PERFORMANCE INSIGHTS',
        total_shipment_sent: 'Total Shipments Sent',
        last: 'Last 30 days',
        cod_noncod: 'COD/Non COD',
        sent_by_product: 'Total Shipments Sent by Product',
        sent_by_state: 'Total Shipments Sent by State',
        top_state_shipments: 'Top States',
        state: 'STATE',
        order_count: 'Order Count',
        percentage: 'Percentage',
        order_sent: 'Order Sent',
        cod: 'COD',
        non_cod: 'NON COD',
        melplus: 'MELPLUS',
        mps: 'MPS',
        pos_laju: 'POS LAJU',
        ems: 'EMS',
        air_parcel: 'AIR PARCEL',
        surface_parcel: 'SURFACE PARCEL',
        delivery_type: 'Delivery Type',
        payment_method: "Payment Method",
        no_data: "No data to display",
        unvailable: "Data unavailable",

      },
      sla: {
        perfomance_insights: 'PERFORMANCE INSIGHTS',
        last_refreshed: 'Last Refreshed',
        download_all: 'Download All',
        report: 'Report',
        shipment_status: 'Shipments Status',
        download_as: 'Download As',
        no_data: 'No data to display',
        delivery_status: 'Delivery Status',
        delivery_status_by_days: 'Delivery Status (By Days)',
        no_available_data: 'No available data',
        delivery_status_by_destination: 'Delivery Status (By Destination)',
        delivery_status_by_percentage: 'Delivery Success By Percentage',
        delivery_status_by_volume: 'Delivery Success By Volume',
        success: 'Success',
        total_shipments: 'Total Shipment',
        delivery_exceptions: 'Delivery Exceptions',
        data_unavailable: 'Data unavailable',
        total_no_of_acceptance: 'Total No. of Acceptance',
        total_no_of_rto: 'Total No. of RTO',
        percentage_of_rto: 'Percentage of RTO',
      },
      not_access_to_mobile: 'This feature isn’t available on mobile. Please use the desktop version to access it.',
      okay: 'Okay'
    },
    menu: {
      home: 'Home',
      shipments: 'Shipments',
      single_shipment: 'Single Shipment',
      bulk_shipment: 'Bulk Shipments',
      my_shipment: 'My Shipments',
      contact: 'Contacts',
      profile: 'My Profile',
      user_profile: 'User Profile',
      billing: 'Billing',
      invoice: 'Invoice',
      logout: 'Log Out',
      reports: 'Reports',
      search: 'Search',
      rate_calculator: 'Rate Calculator',
      user_management: 'User Management',

      linked_account: 'Linked Accounts',
      available_account: 'Available Accounts',
      company_name: 'Company Name',
      account_number: 'Account Number',
      type: 'Type',
      permission: 'Permissions',
      switch_account_failed: 'Switch account failed',
      ok: 'ok',
      view_account: 'View Account',
      master: 'Master',
      sub: 'Sub',
      set_as_default: 'Set as Default',
      default_account: 'Default Account',

      select_all: 'Select All',
      date_range: 'Date Range',
      required_date_range: 'Please select date range',
      shipment_status: 'Shipment Status',
      required_shipment_status: 'Select Shipment Status',
      payment_type: 'Payment Type',
      required_payment_type: 'Select Payment Type',
      product: 'Product',
      required_product: 'Select Product',
      reset_filter: 'Reset Filters',
      search_by: 'Search by tracking no, name, email or phone no.',
      more: 'More',
    },
    pickupCardList: {
      pick_up_address: 'Pick Up Address',
      add_pick_up_address: '+ Add Pick Up Address',
      select_address_list: 'Select Pick Up Address from the list below',
      return_address: 'Select return address from list below',
      please_note: 'Please note',
      change_note: 'Pick Up Address for bulk shipment order cannot be changed.',
      next: 'Next',
      note1: 'There are no Pick Up',
      note2: 'Addresses available.',
      note3: 'To start shipping your items,',
      note4: 'please add a Pick Up Address.',
    },
    recipientDetail: {
      loading: 'Loading',
      edit: 'Edit',
      no_record_found: 'No records found.',
      recipient_details: 'Recipient Details',
      search_contact: 'Search Contacts',
      search: 'Search',
      search_placeholder: 'Search Name, Address, or Company',
      no_result: 'No result',
      email_note:
        'Note: You can edit/ update the auto-generated address or input your own address.',
      postcode_require_message: 'Enter 0000 if there is no postcode',
      save_contact: 'Save to Contacts',
      next: 'Next',
      search_contact_error_message: 'Something went wrong!',
      invalid_sender_postcode:
        'Invalid sender postcode. Please provide a valid postcode to proceed',
    },
    bulkShipment: {
      bulk_shipment: 'Bulk Shipments',
      bulk: 'Bulk',
      shipment: 'Shipments',
      template: 'template',
      home: 'Home',
      domestic: 'DOMESTIC',
      domestic_lower: 'Domestic',
      international: 'International',
      below: 'below',
      download_the: 'Download the',
      contact_upload: 'Contacts Upload',

      steps_to_create: 'Steps on how to create',
      bulk1: 'bulk',
      shipment1: 'shipments',
      should_there_be_errors:
        'Should there be errors with your uploaded file, download error file from the pop up message.',
      edit_and_reupload:
        'Edit highlighted field(s) in the error file with correct details and re-upload your amended file.',

      within_east_west: 'For shipments within East and West Malaysia only',
      outside_malasiya: 'For shipments outside of Malaysia',
      contact_upload_note:
        'Each file upload can include up to a 1000 contacts.',
      contact_upload_templete: 'Contact Bulk Upload Template',
      upload_bulk_file:
        'Upload the filled bulk file by dropping it here or by clicking Upload from Computer.',
      generate_connotes: 'Generate consignment notes.',
      click_submit: 'Click Submit',
      upload_compoter: 'Upload from Computer',
      add_contacts:
        'Add your contacts into the fields provided in the template.',
      add_contacts_important_note:
        'Important Note: Do not delete any column from the template.',
      add_contacts_own_format:
        'Simply add contacts of your own by following the given format.',
      successful_upload: 'To ensure successful upload:',
      please_use: 'Please use the',
      latest_template: 'latest template',
      provided_above: 'provided above.',
      alter_template:
        "Please don't alter the template (Excel file), add/remove columns etc.",
      file_error:
        'If your uploaded file shows errors, please download the error file.',
      error_details:
        'The error file will show the exact error details. Please fix and re-upload the same error file.',
      drop_file: 'Drop your .xls, .xlsx, .xlsm file here',
      or: 'or',
      hs_code_list: 'Provide HS Code and Country Code based on the list',
      here: 'here',

      required_image: 'Please select an image',
      Uh_oh: 'Uh-oh',
      found_error_in_upload: 'we found error in your uploaded file',
      require_templete_contact_excel:
        'Please use relevant contact excel template',
      templete_outdated:
        'Your bulk shipment template seems to be outdated/ not in the correct format. Please download the latest template and reupload the file.',
      error_while_upload:
        'Something went wrong while uploading bulk file, please try again later',
      error_not_as_per_templete:
        'Your bulk file is not as per the template, please re-check your file and try again',
      error_domestic_templete: 'Please use Domestic CODUbat template',
      error_domestic_cod_templete: 'Please use Domestic COD template',
      error_domestic_noncod_templete: 'Please use Domestic Non COD template',
      error_melplus_templete: 'Please use MelPlus template',
      error_mps_templete: 'Please use MPS template',
      error_international_templete: 'Please use International template',
      success_added_contact:
        'Recipient(s) successfully added into your contacts.',
      error_empty_field:
        'There seem to be empty fields/errors in the fields. Please correct the info and reupload the file.',
      error_multiple:
        'One or more fields in the file was found to be incorrect or insufficient. The results have been compiled in the downloaded file. Please amend the fields and reupload them again to continue with your request.',
      download: 'Download',
    },
    myShipments: {
      home: 'Home',
      shipment: 'Shipment',
      shipment_detail: 'Shipment Details',
      my_shipments: 'My Shipments',
      edit_order: 'Edit Order',
      request: 'REQUEST',
      for_pickup: 'FOR PICK UP',
      pending: 'PENDING',
      shipments: 'SHIPMENTS',
      live: 'LIVE',
      live_shipment: 'SHIPMENTS',
      delivered: 'DELIVERED',
      failed: 'FAILED',
      deliveries: 'DELIVERIES',
      return: 'RETURN',
      return_shipments: 'SHIPMENTS',
      all: 'All',
      tracking_details: 'TRACKING DETAILS',
      recipient: 'RECIPIENT',
      parcel: 'PARCEL',
      delivery_detail: 'DELIVERY DETAILS',
      to: 'to',
      action: 'ACTION',
      type: 'TYPE',
      pick_up_date: 'PICK UP DATE',
      pick_up_info: 'PICK UP INFO',
      no_tracking_id: 'NO TRACKING ID GENERATED',
      not_scheduled: 'PICK UP NOT SCHEDULED',
      pick_up_scheduled: 'PICK UP SCHEDULED',
      pick_up_re_scheduled: 'PICK UP RESCHEDULED',
      pick_up_cancelled: 'PICK UP CANCELLED',
      partial_picked_up: 'PARTIALLY PICKED UP',
      pending_drop_off: 'PENDING DROP-OFF',
      in_transit: 'IN TRANSIT',
      picked_up: 'PICKED UP',
      out_for_delivery: 'OUT FOR DELIVERY',
      self_collect: 'SELF COLLECT',
      dropped_off: 'DROPPED-OFF',
      pickup_failed: 'PICK UP FAILED',
      returned_table: 'RETURNED',
      return_sender: 'RETURN TO SENDER',
      return_success: 'RETURNED',
      pick_up_address: 'Pick up Address',
      weight: 'WEIGHT (KG)',
      reason: 'REASON',
      store: 'STORE',
      channel: 'CHANNEL',
      non_cod: 'NON COD',
      download: 'Download',
      commercial_invoice: 'Commercial Invoice (.pdf)',
      get_consignment_note: 'Get Consignment Note',
      no_data: 'No data',
      delay_in_delivering:
        "Uh-oh, there's a delay in delivering this page. Please",
      refresh: 'refresh',
      update: 'Update',
      add: 'Add',
      remove_user: 'Remove User',

      order: 'Order(s)',
      selected: 'selected',

      no_tracking_id2: 'No Tracking Id',
      pick_up_not_scheduled: 'Pick Up Not Scheduled',
      all2: 'All',

      add_order_to_pickup: 'Add Order to Pick Up',
      cancel_shipment: 'Cancel & Delete Shipment',
      reschedule: 'Reschedule',
      cancel: 'Cancel',
      cancelled: 'CANCELLED',
      edit_shipment: 'Edit Shipment',
      delete_shipment: 'Delete Shipment',
      delete_store: 'Delete Store',
      track: 'Track',
      view: 'View',
      print: 'Print',

      request_pickup_note: 'Request Pick Up',
      pending_pickup_note: 'Pending Pick Up',
      live_shipments_note: 'Live Shipments',
      delivered_note: 'Delivered',
      failed_deliveries_note: 'Failed Deliveries',
      returned_note: 'Returned',
      pickup_details_note: 'Pick up details',

      status: 'STATUS',
      qty: 'QTY',

      thermal_label: 'Thermal Label',
      tallysheet: 'Tallysheet',

      parcel_dimensions_guide: 'Parcel Dimensions Guide',
      page_copy_note:
        'Fill in the form below and your shipment will be on your way.',
      page_title: 'Send a single shipment',

      invalid_sender_postcode:
        'Invalid sender postcode. Please provide a valid postcode to proceed',
      close: 'Close',
      prepare_to_deliver: 'PREPARING TO DELIVER',
      proof_of_delivery: 'Proof of Delivery',
      view_proof_of_delivery: 'View Proof of Delivery',
      no_result_to_display: 'No results to display',
      pending_cancellation: 'PENDING CANCELLATION APPROVAL',
      order_created: 'ORDER CREATED',
      processing_return: 'PROCESSING RETURN',
      return_initiated: 'RETURN INITIATED',
      failed_delivery_attempt: 'FAILED DELIVERY ATTEMPT',
      on_the_way: 'ON THE WAY',
      out_for_return: 'OUT FOR RETURN',
      pick_up_assigned: 'PICK UP ASSIGNED',
      ready_to_collect: 'READY TO COLLECT',
      return_failed: 'RETURN FAILED',

      request_pickup: {
        search_tracking: 'Search Tracking ID',
        search_tracking_placeholder: 'Search tracking no. or recipient name',
        date_range: 'Date Range',
        create_consignment: 'Create Consignment and Pick up',
        get_consignment: 'Get Consignment and Note',
        download_as: 'Download as',
        commercialinvoice: 'Commercial Invoice',
        delete: 'Delete',
        no_record_found: 'No records found.',
        description1:
          'You can download up to 100 consignment notes at one time. Please unselect the remaining consignment notes to proceed with the download action.',
        print_title: 'Print Consignment Note',
        description2:
          'Please go to Pending Shipments tab to print consignment note. Thank You!',
        generate_consigment_note: 'Generate Consignment Note',
        print_label: 'Print Label',
        download_consignment_note: 'Download Consignment Note',
        download_tallysheet: 'Download Tallysheet',
        download_consignment_invoice: 'Download Commercial Invoice',
        delete_order: 'Would you like to delete the order(s)?',
        dailog_title: 'Uh-oh',
        pickup_message: 'This is a static message.',
        dailog_msg1: 'Are you sure you want to',
        dailog_msg2: 'for this',
        thermal_label: 'Thermal Label',
        tallysheet: 'Tallysheet',
        go_now: 'Go Now',
      },
      pending_shipments: {
        search_shipments: 'Search Shipments',
        search_shipments_placeholder:
          'Search Shipments by pickup no and connote no',
        date_range: 'Date Range',
        order_status: 'Order Status',
        order_status_placeholder: 'Select Order Status',
        order_status_all: 'All',
        order_status_pickup_schedule: 'Pick Up Scheduled',
        order_status_pickup_reschedule: 'Pick Up Rescheduled',
        order_status_partial: 'Partial Picked Up',
        order_status_dropoff: 'Pending Drop Off',
        view_by: 'View By',
        orders: 'Orders',
        pickup_number: 'Pickup Number',
        print_label: 'Print Label',
        download_as: 'Download as',
        thermal_label: 'Thermal Label',
        tallysheet: 'Tallysheet',
        commercialinvoice: 'Commercial Invoice',
        no_record_found: 'No record Found',
        cancel_pickup_note:
          'Are you sure to cancel this Pick Up? You will need to schedule a new Pick Up after cancellation.',
        reschedule_pickup_title: 'Would you like to make a Pick Up Request',
        reschedule_pickup_description:
          'Select your preferred Pick Up date below. Pre-selected Pick Up dates will be based on the closest date (before cut off time).',
      },
      live_shipment_tab: {
        search_orders: 'Search Orders',
        search_orders_placeholder: 'Search tracking no. or recipient name',
        all: 'All',
        order_type: 'Order Type',
        picked_up: 'Picked Up',
        date_range: 'Date Range',
        order_status: 'Order Status',
        in_transit: 'In Transit',
        out_for_delivery: 'Out For Delivery',
        dropped_off: 'Dropped Off',
        non_cod: 'NON COD',
        select_order_status: 'Select Order Status',
        select_order_type: 'Select Order Type',
        print_label: 'Print Label',
        download_as: 'Download As',
        thermal_label: 'Thermal Label',
        tallysheet: 'Tallysheet',
        commercial_invoice: 'Commercial Invoice',
      },
      delivered_tab: {
        search_orders: 'Search Orders',
        all: 'All',
        non_cod: 'NON COD',
        date_range: 'Date Range',
        order_type: 'Order Type',
        search_orders_placeholder:
          'Enter tracking no., name, location or contact no.',
        select_order_type: 'Select Order Type',
        print_label: 'Print Label',
        download_as: 'Download As',
        thermal_label: 'Thermal Label',
        tallysheet: 'Tallysheet',
        commercial_invoice: 'Commercial Invoice',
      },
      failed_deliveries: {
        search_orders: 'Search Orders',
        all: 'All',
        non_cod: 'NON COD',
        date_range: 'Date Range',
        order_type: 'Order Type',
        search_orders_placeholder:
          'Enter tracking no., name, location or contact no.',
        select_order_type: 'Select Order Type',
        print_label: 'Print Label',
        download_as: 'Download As',
        no_record_found: 'No Record Found',
        thermal_label: 'Thermal Label',
        tallysheet: 'Tallysheet',
        commercial_invoice: 'Commercial Invoice',
      },
      returned: {
        search_orders: 'Search Orders',
        all: 'All',
        non_cod: 'NON COD',
        date_range: 'Date Range',
        order_type: 'Order Type',
        search_orders_placeholder:
          'Enter tracking no., name, location or contact no.',
        select_order_type: 'Select Order Type',
        print_label: 'Print Label',
        download_as: 'Download As',
        thermal_label: 'Thermal Label',
        tallysheet: 'Tallysheet',
        commercial_invoice: 'Commercial Invoice',
      },
      parcel_data: {
        edit: 'Edit',
        parcel_detail: 'Parcel Details',
        view_guide: 'View Guide',
        document: 'Document',
        parcel: 'Parcel',
        mps: 'MPS',
        ubat: 'Ubat',
        mel_plus: 'MelPlus',
        parcel_note: 'Parcel Notes',
        sender_ref: 'Sender Ref No',
        my_parcel_requires: 'My parcel requires',
        mymel_parcel_requires: 'Mymel parcel requires',
        cash_on_delivery: 'Cash On Delivery',
        cash_on_delivery2: 'Cash On Delivery',
        shipping_insurance: 'Pos Service Warranty',
        shipping_note1: 'Protect your shipments for as little as ',
        shipping_note2: '1% of the declared value.',
        insurance_note1_bold: 'Ship with confidence ',
        insurance_note1:
          'knowing your items are handled with extra care to prevent loss or damage. For details on service warranties, exclusions, and packaging guidelines, ',
        insurance_note2: 'click here',
        insurance_note4_1_bold: 'General Items',
        insurance_note4_1: ' - Enjoy Reimbursement up to RM5,000',
        insurance_note4_1_tootlTip:
          'Standard packaged goods that are non-fragile and solid in nature, such as books, clothes, and electronics.',
        insurance_note4_2_bold: 'Non-Solid or Fragile Items',
        insurance_note4_2: ' – Reimbursement up to RM1,000',
        insurance_note4_2_tootlTip:
          'Items that are delicate, easily breakable, or not in solid form, such as skincare, glassware, ready-to-eat foods, and powders (for delivery within Peninsular Malaysia / within Sabah / within Sarawak).',
        insurance_note5:
          'Maximum value protected for all multi-piece shipments is up to RM10,000 only.',
        custom_declaration_form: 'Customs Declaration Form',
        what_are_you_shipping: 'What are you shipping?',
        shipment_rate_note:
          'Shipment rate will be calculated based on parcel weight or volumetric weight whichever is higher',
        declare_more_item: 'Declare More Items',
        weight_tooltip:
          'Shipment rate will be calculated based on parcel weight or volumetric weight whichever is higher',
        melplus_tooltip:
          'Shipment rate is based on zone and weight band (in kg).',
        product_list_fail_note: 'Failed to get the list of products',
        origin_country: 'Origin Country',

        multi_piece_shipment_detail: 'Multi-Piece Shipment Details',
        add_shipment: 'Add Shipment',
        invalid_sender_postcode:
          'Invalid sender postcode. Please provide a valid postcode to proceed',
      },
      mps_details: {
        home: 'Home',
        my_shipment: 'My Shipments',
        mps_details: 'MPS Details',
        pickup_Details: 'Pick up Details',
        multi_piece_shipment_details: 'MULTI-PIECE SHIPMENT DETAILS',
        parent_consignment_note: 'Parent Consignment Note',
        total_shipment: 'Total Shipments',
        total_weight: 'Total Weight (Kg)',
        print_label: 'Print Label',
        download_as: 'Download as',
        back_to_pickup: 'Back to Pick Up',
        back_to_pickup_detail: 'Back to Pick up Details',

        thermal_label: 'Thermal Label',
        tallysheet: 'Tallysheet',
        commercialinvoice: 'Commercial Invoice',
      },
    },
    pickup_details: {
      pickup_details_title: 'Pick up Details',
      pick_up_no: 'Pick Up No.',
      pick_up_date: 'Pick up Date',
      pick_up_address: 'Pick up Address',
      total_parcel: 'Total Parcel',
      total_weight: 'Total Weight (Kg)',
      change_pick_up_date: 'Change Pick Up Date',
      add_orders: 'Add Orders',
      print_label: 'Print Label',
      download_as: 'Download As',
      home: 'Home',
      my_shipments: 'My Shipments',
      back_data: 'Back to Pick Up',
    },
    order_details: {
      reason: 'Reason',
      order_details: 'Order Details',
      tracking_details: 'Tracking Details',
      tracking_no: 'Tracking No.',
      store_info: 'Store info',
      order_date: 'Order Date',
      order_time: 'Order Time',
      print_label: 'Print Label',
      tracking_history: 'Tracking History',
      proof_of_delivery: 'Proof of Delivery',
      no_record_found: 'No Record Found',
      sender_details: 'Sender Details',
      recipient_details: 'Recipient Details',
      parcel_details: 'Parcel Details',
      product_name: 'Product Name',
      category: 'Category',
      category_details: 'Category Details',
      dimensions: 'Dimensions(cm)',
      parcel_weight: 'Parcel Weight(kg)',
      volumetric_weight: 'Volumetric Weight(kg)',
      chargeable_weight: 'Chargeable Weight(kg)',
      sum_insured: 'Sum insured (RM)',
      insurance_premium: 'Insurance Premium (RM)',
      cod_amount: 'COD Amount (RM)',
      item_description: 'Item Description',
      parcel_notes: 'Parcel Notes',
      custom_declarations: 'Custom Declarations',
      weight: 'Weight (kg)',
      Quantity: 'Quantity',
      hs_code: 'HS Code',
      value_rm: 'Value (RM)',
      country_of_origin: 'Country of Origin',
      download: 'Download',
      home: 'Home',
      my_shipments: 'My Shipments',
      error_note1: 'Error while downloading. Please try again.',
      close: 'Close',
      print: 'Print',
      track_order: 'Track Order',
      status: 'Status',
      back_data: 'Back to Pick Up',

      back_data_detail: 'Back to Pick up Details',
      pickup_detail: 'Pick up Details',
      mps_detail: 'MPS Details',
      back_to_MPS_details: 'Back to MPS Details',

      add_orders: 'Add Orders',
      pickup_no: 'Pick Up No.',
      pickup_date: 'Pick Up Date.',
      pickup_address: 'Pickup Address.',
      add_pickup: 'Add to Pick Up',
      no_data_found: 'No data found',
      generate_consignment_note: 'Generate Consignment Note',
      action_note1: 'Are you sure you want to',
      action_note2: 'for this order?',
      add_orders_to_pickup:
        'Are you sure you want to add these Orders into this Pick Up No.?',
      static_message: 'This is a static message.',
      create_reverse_pick_up: 'Create Reverse Pick Up',
      updated_on: 'Updated On',
      uh_oh: 'Uh-oh',
      sender_ref: 'Sender Ref No',
      convert_to_non_cod: 'Convert to Non COD',
      confirm_convert_to_non_cod: 'Yes, Convert to Non COD',
      confirm_cancel_button_to_non_cod: 'Ok, got it',
      cancel_button_to_non_cod: 'Cancel',
      cannot_convert_to_non_cod: 'Cannot convert to Non COD',
      message_convert_to_non_cod:
        'Are you sure you want to change<br>the COD amount of',
      to_non_cod: 'to Non COD?',
      failed_to_convert_to_non_cod:
        'Oops, failed to update your payment to Non COD.',
      failed_to_convert_to_not_available:
        'Sorry, COD is not available for this account',
      cancel_shipment: 'Cancel Shipment',
      delete_shipment: 'Delete Shipment',
      confirm_delete_shipment: 'Are you sure you want to delete this shipment?',
      confirm_delete_mps:
        'Are you sure you want to delete the parent shipment? <br> This action will also delete all associated shipments.',
      confirm_cancel_shipment:
        'Are you sure you want to delete this shipment? <br> Once deleted, it cannot be picked up or dropped off.',
      failed_cancel_shipment: 'Failed to confirm shipment',
    },
    profile: {
      home: 'Home',
      my_profile: 'MY PROFILE',
      pickup: 'PICK UP',
      address: 'ADDRESS',
      delete: 'Delete',
      pickup_address: 'Pick Up Address',
      select_address_list:
        'Select Pick Up Address from the list below to view and edit details or add a new address',
      save_default_address: 'Save as Default Address',
      update: 'Update',
      submit: 'Submit',
      remove_user: 'Padam Pengguna',
      save: 'Save',
      search_contact: 'Search Contacts',
      company: 'Company Name',
      personal_details: 'Personal Details',
      my_addresses: 'My Addresses',
      hide_address: 'Hide Address',
      hide_pickup_address: 'Yes, hide my pick up and return address',
      hide_address_note:
        'Note: Your addresses will now be hidden from the recipient.',
      hide_address_confirm: 'Confirm',
      address_update_toaster: 'Hide address preference is updated.',
      address_update_toaster_error:
        'Oops. Hide address preference is not updated.',
      fetch_config_error: 'Error fetching configuration:',
    },
    contact: {
      create_contact: 'CREATE CONTACT',
      home: 'Home',
      contact: 'Contact',
      sort_all_contact: 'Sort all of your contact with ease',
      create_new_contact: 'Create New Contact',
      create_new_contact1: 'CREATE NEW CONTACT',
      contact_all: 'MY CONTACT (ALL)',
      search: 'Search Contact',
      delet: 'Delete',
      download: 'Download All',
      contact_person: 'CONTACT PERSON',
      contact_no: 'CONTACT NO.',
      email: 'EMAIL',
      address: 'ADDRESS',
      company: 'COMPANY',
      shipments: 'Shipments',
      create__contact: 'Create Contact',
      save_contact: 'Save Contact',
      recipient_name: 'Recipient Name',
      add_contact_note: 'Are you sure you want to add this contact?',
      bulk_upload: 'Bulk Upload',
      would_like_to_delete: 'Would you like to delete the selected',
    },
    billing: {
      billing: 'Billing',
      download: 'Download',
      back_data: 'Back to Pick Up',
      invoices: 'Invoices',
      invoice_date: 'Invoice date',
      invoice_no: 'Invoice Number',
      period: 'Period',
      amount: 'Amount',
      action: 'Action',
      no_data_is_available: 'No data is available',
      invalid_date: 'Invalid Date',
      date_time: 'Date/Time',

      online_payment: 'ONLINE PAYMENT',
      important_notice: 'Important Note',
      please_select_invoice:
        'Please select your invoice(s) to make online payment.',
      payment_note:
        'Once paid, it can take up to 24 hours for your account status to be updated in SendParcel Pro.',
      payment_status:
        'If your payment status is "Pending", system will update to the latest status within 2 hours.',
      pay_now: 'Pay Now',
      invoice_selected: 'invoices selected',
      already_paid_error:
        'These selected invoices may already contain paid items.',

      pending: 'PENDING',
      paid: 'PAID',
      failed: 'FAILED',
      home: 'Home',
    },
    pickup_data: {
      update: 'Update',
      add: 'Add',
      pick_up_address: 'Pickup Address',
      send_shipment_note: 'Send a single shipment',
      delete_address_note:
        'Are you sure you want to delete this pickup address?',
      delete_address_note2: 'Pickup Address has been deleted Successfully!',
      close: 'Close',
      update_address_note:
        'Are you sure you want to update this pickup address?',
      personal_details: 'Personal Details',
    },
    dialog_box_data: {
      successful: 'successful',
      note: 'Please proceed to pending shipments tab for printing consignment notes',
      failed: 'failed',
      request_pickup: 'Please retry requesting for pickup',
      error_msg: 'One or more data are incorrect, please try again later.',
      error_title: 'We found error while submission!',
      confirm: 'Confirm',
      error_message1: "We're facing a system error. Please try again shortly.",
      error_message2:
        "We've a failure in this delivery. Please re-try. Thank you.",
      error_message3:
        'It seems that your account is blocked. Please contact your Account Manager for assistance.',
      error_message4:
        "We're unable to process this request. Please try again later.",
      error_message5: 'Something went wrong. Please try again later.',
      error_message6:
        'Your account is not active. Please contact account owner for details.',
      error_message7: 'This user does not have the required access.',

      need_at_least_one_connote:
        'Need at least 1 connote ID to add item into request pickup',
      no_record_to_download:
        'Oops, there is no result found for the searched criteria',
      duration_of_days: 'Duration is more than 90 days',
      yes: 'Yes',
      cancel: 'Cancel',
      uh_oh: 'Uh-oh',
      close: 'Close',
      three_months_limit: 'Only three months can be selected'
    },
    smart_fill_data: {
      title: 'Smart Fill',
      note1:
        "Paste receiver details in any order and we'll fill out the fields for you ",
      note2: '(Malaysian addresses only).',
      note3: 'E.g. Muhammad Ali',
      note4: '0125456789',
      note5: '51, Dayabhumi Complex 50480 Kuala Lumpur',
      note6: 'muhammad.ali@gmail.com',
      submit: 'Submit',
    },
    report: {
      reports: 'Reports',
      generate_a_report: 'GENERATE A REPORT',
      select_date_range: 'Select date Range',
      filter_by_status: 'Filter by Status',
      required_filter: 'Please select one or more',
      generate_report: 'Generate Report',
      result: 'RESULT',
      date: 'Date',
      file_name: 'File Name',
      action: 'Action',
      all: 'All',
      pickup_requested: 'Pick Up Scheduled',
      pickup_rescheduled: 'Pick Up Rescheduled',
      out_for_delivery: 'Out for Delivery',
      picked_up: 'Picked Up',
      droppedoff: 'Dropped Off',
      in_transit: 'On The Way',
      delivered: 'Delivered',
      returned: 'Returned',
      failed: 'Failed Delivery Attempt',
      cancelled: 'Cancelled',
      cod: 'COD',
      non_cod: 'NON COD',
      order_created: 'Order Created',
      pickup_failed: 'Pick Up Failed',
      to_collect: 'Ready For Collection',
      collected: 'Collected',
      return_failed: 'Return Failed',
      report_error_note:
        'Only a maximum of 5 Reports can be generated at one time.',
      report_generated_successfully: 'Report Generated Successfully!',
      please_fill_the_form: 'please fill the form',
      file_not_available: 'File is not available to download',
      close: 'Close',
      no_record_to_download:
        'Oops, there is no result found for the searched criteria',
      duration_of_days: 'Duration is more than 90 days',
      home: 'Home',
    },
    rate_calulator: {
      pos_laju_shipment_rate_calculator: 'POS LAJU SHIPMENT RATE CALCULATOR',
      shipment_rate_calculator: 'Shipment Rate Calculator',
      rate_card: 'Rate Card',
      shipment_details: 'Shipment Details',

      calculating: 'Calculating...!',
      generate_quote: 'Generate Quote',
      important_note: 'Important Note:',
      note1:
        'Kindly save your custom rate card in the designated section below to maximize the functionality of the rate calculator.',
      note2:
        'This calculator is specifically designed for domestic Pos Laju shipments and should be used accordingly.',
      note3:
        'Please note that the total price generated by the calculator serves as an estimate only. For precise billing information, always refer to your invoice.',
      note4:
        'It is advisable to regularly cross-check the rates mentioned in the rate card section to ensure accuracy and alignment with your pricing agreements.',
      shipment_rate: 'Shipment Rate',
      estimated_total: 'Estimated Total',

      to_edit_rate_card: 'How to edit your Rate Card:',
      input_your_rates: 'Input your rates:',
      input_your_rates_note:
        'Please enter your rates in the provided fields to make effective use of the rate calculator.',
      rate_inpute_requirement: 'Rate input requirements:',
      rate_inpute_requirement_note:
        'Your rates should be input for Zones 1, 2, 3 / Zone 4 / Zone 5. Refer to the pricing agreement for the specific rates and zone information.',
      example: 'Example',
      example_note:
        'For Zones 1, 2, 3, the rate for the first 3kgs is RM 6, and the additional rate per kg is RM 1.50.',
      example_note1: 'To input these rates:',
      example_note2:
        'In the Zone 1, 2, 3 (blue) section, use the weight dropdown to select 3.',
      example_note3: 'Input 6 in the price field.',
      example_note4:
        'Select 1 in the additional (per kg) field and input 1.50 in the price field.',
      example_note5: 'Click "Save & Apply" to confirm the changes.',

      additional: 'Additional (per kg)',
      zone: 'Zone',
      add_weight: 'Add Weight',
      amount_exceed: "Amount can't exceed RM100",
      min_amount: 'Enter a minimum of RM1',
      price: 'Price (RM)',
      add_additional_weight: 'Add Additional Weight',
      set_price: 'Set Price',

      close: 'Close',
      error_while_fetching_rate_calculation_data:
        'An error occurred while fetching rate calculation data.',
      no_rate_cards_available: 'No rate cards available.',
      error_while_fetching_rate_data:
        'An error occurred while fetching rate cards.',
      failed_to_fetch_data: 'Failed to fetch data',
      configure_your_rate_card:
        'Please configure your rate card in the section below to use this calculator.',
      error_fetching_zone_data: 'Error fetching zone data. Please try again.',
      zone_information_not_available: 'Zone information not available.',
      invalid_weight_input: 'Invalid weight input.',
      error_calculating_shipping_cost: 'Error calculating shipping cost.',
      invalid_postcode: 'Invalid postcode',
      no_rate_card_found_for_zone: 'No rate card found for zone',
      your_rate_card_has_been_configured: 'Your rate card has been configured.',
      your_rate_card_is_not_configured: 'Your rate card is not configured.',
      rate_calculator: 'Rate Calculator',
      home: 'Home',
    },
    user_management: {
      home: 'Home',
      my_profile: 'My Profile',
      user_management: 'User Management',
      add_user: 'Add User',
      name: 'Name',
      email_address: 'Email Address',
      resend: 'Resend',
      account_access: 'Account Access',
      status: 'Status',
      not_activated: 'Not activated',
      action: 'Action',
      no_data_available: 'NO DATA AVAILABLE',

      are_you_confirmed_to_remove_this_user:
        'Would you like to remove this user?',
      are_you_confirmed_to_remove_this_user_note:
        'This action is permanent. User will no longer have access to SendParcel Pro account',
      user_has_been_deleted_successfully: 'User has been removed successfully',
      ok: 'Ok',
      email_has_been_sent_successfully: 'email has been sent successfully',
      resend_email_has_been_failed: 'resend email has been failed',

      full_name: 'Full Name',
      please_enter_your_name: 'Please enter your name',
      account: 'Account',
      more: 'More',
      please_select_an_account: 'Please select an account',
      please_select_one_or_more: 'Please select one or more',
      require_email: 'Please enter your email',
      require_valid_email: 'Please enter a valid email address',
      email_example: 'yourname@example.com',
      update: 'Update',
      remove_user: 'Remove User',
      submit: 'Submit',
      update_user: 'Update User',
      send_email1: 'An email was sent to',
      send_email2: 'The receiver is required to create login credentials.',
      ok_got_it: 'Ok, got it',
      email_msg1: 'Email',
      email_msg2: 'already exist',
      user_creation_failed: 'User creation failed',
      error_msg1: 'Oops, user does not have the required access.',
      error_msg2: 'User has been updated successfully',
      error_msg3: 'Default Account can’t be removed from user access.',
      error_msg4: 'Something went wrong. Please try again later.',
    },
    form_data: {
      // // error handling
      three: 3,
      five: 5,
      seven: 7,
      eight: 8,
      ten: 10,
      minlength: 'Minimum of',
      characters: 'characters',

      required_receipent: "Enter recipient's name",
      required_company: 'Enter company name',
      required_receipent_address: "Enter recipient's addresss",
      required_receipent_email: "Enter recipient's email addresss",
      required_valid_email: 'Enter valid email address',
      required_receipent_postcode: "Enter recipient's postcode",
      required_valid_postcode: 'Enter valid postcode',
      invalid_postcode: 'Postcode is invalid',
      required_state: "Recipient's state is required",
      required_city: "Recipient's city is required",
      required_pickup: 'Enter Pickup Name.',
      required_pickup_postcode: 'Masukkan Poskod Pickup.',

      country: 'Country',
      required_country: 'Country is required',

      code: 'Code',
      required_code: 'Dial Code is required',
      phone: 'Phone',
      required_phone: 'Phone No. is required',
      required_valid_phone: 'Enter valid phone',
      required_name: 'Enter name',

      search: 'Search',
      no_result: 'No result',

      recipient_name: 'Recipient Name',
      company_name: 'Company Name',
      email_address: 'Email Address',
      address: 'Address',
      postcode: 'Postcode',
      state: 'State',
      city: 'City',
      name: 'Name',

      save_default_address: 'Save as Default Address',
      add_pickup_address: 'Add Pickup Address',
      update: 'Update',
      submit: 'Submit',
      save: 'Save',
      delete: 'Delete',
      save_changes: 'Save Changes',
      complete: 'Complete',
      save_to_contact: 'Save to Contacts',
      close: 'Close',
      back: 'Back',
      amountError: 'Amount is required and must be a valid number.',
      validAmount: 'Please enter a valid number for amount.',
      codCheckboxError:
        'An unexpected error occurred while processing the COD checkbox.',
      minAmountError: 'Amount is required and must be between 1 and ',
      unexpectedError: 'An unexpected error occurred. Please try again later.',
      editing_not_allowed_error:
        'Oops, editing order is not allowed after pick up has been assigned to courier.',

      category: 'Category',
      required_category: 'Select parcel category',
      no_of_shipments: 'No. of Shipments',
      width: 'Width (cm)',
      required_width: 'Enter width in cm',
      required_valid_width: 'Enter valid width',
      length: 'Length (cm)',
      required_length: 'Enter length in cm',
      required_valid_length: 'Enter valid length',
      height: 'Height (cm)',
      required_height: 'Enter height in cm',
      required_valid_height: 'Enter valid height',
      total_weight: 'Total Weight (Kg)',
      weigth: 'Weight (kg)',
      required_weight: 'Enter weight in kg',
      required_valid_weight: 'Enter valid weight',
      volumetric_weight: 'Volumetric Weight (kg)',
      chargeable_weight: 'Chargeable Weight(kg)',
      required_volumetric_weight: 'Volumetric Weight is required',
      required_chargeable_weight: 'Chargeable Weight is required',
      description_content: 'Description of Content',
      sender_ref: 'Sender Ref No',
      required_description_content: 'Description is required',
      amount: 'Amount (RM)',
      required_amount: 'Enter Amount (RM)',
      required_valid_amount: 'Enter valid amount',
      required_min_amount: 'Minimum amount is RM1',
      required_max_amount: 'COD amount exceeds limit',
      required_max_amount_exceeds_limit: 'Exceeds max amount allowed',
      sum_insured: 'Declared Value (RM)',
      required_sum_insured: 'Enter Sum Insured (RM)',
      required_valid_sum_insured: 'Enter valid insured amount',
      required_min_sum_insured: 'Minimum amount is RM1',
      required_max_sum_insured: 'Maximum value up to RM5,000',
      premium_amount: 'Warranty Rate (RM)',
      required_valid_premium_amount: 'Enter valid premium amount',
      product: 'Product',
      select_product: 'Select parcel product',
      category_detail: 'Category Details',
      required_category_detail: 'Select parcel category detail',
      item_description: 'Item Description',
      required_item_description: 'Enter Item Description',
      quantity: 'Quantity',
      required_quantity: 'Enter quantity',
      required_valid_quantity: 'Enter valid quantity',
      value: 'Value (RM)',
      required_value: 'Enter value in RM',
      required_valid_value: 'Enter valid value in RM',
      extra_charges_warning_message:
        'Extra charges will incur for parcels exceeding the weight limit and dimension limit',
      total_sum_insured: 'Declared Value (RM)',
      required_total_sum_insured: 'Maximum value up to RM10,000',
      parent_shipment: 'Parent Shipment',
      child_shipment: 'Child Shipment',
      pickup_added_success_note: 'Pickup Address has been added Successfully',

      created: 'created',
      updated: 'updated',
      create_shipment: 'Create Shipment',
      get_consignment_note: 'Get Consignment Note',
      request_for_pickup: 'Request for Pick Up',
      shipment_is: 'Your shipment has been ',
      please_proceed_to: 'Please proceed to',
      generate_consignment_note: 'Generate Consignment Note',
      download_consignment_note:
        'Please download & print your updated consignment note',
      continue: 'Continue',
      download: 'Download',
      do_you_wish_to_create_more_orders: 'Do you wish to create more orders?',
      create_more_orders: 'Create More Orders',

      pickup_request: 'Would you like to make a Pick Up Request?',
      date_range: 'Date Range',
      select_date: 'Select Date',
      edit_date: 'Edit Date',
      date_note:
        'Select your preferred Pick Up date below. Pre-selected Pick Up dates will be based on the closest date (before cut off time).',
      edit_date_note: 'To schedule pick up to other date, click “Edit Date',
      request_pickup: 'Request for Pick Up',
      required_date: 'Date is required',
      required_valid_date: 'Field is not a valid date.',
      required_current_date: 'Date cannot be in the past.',
      parcel: 'Parcel',
      document: 'Document',
      merchandise: 'Merchandise',
      gift: 'Gift',
      sales_of_goods: 'Sales of Goods',
      commercial_sample: 'Commercial Sample',
      returned_goods: 'Returned Goods',
      others: 'Others',

      state_from: 'State From',
      state_to: 'State To',
      max_weight_30kg: 'Max. Weight : 30kg',
      max_weight: 'Exceeds maximum weight.',
      required_weight_more_than_0: 'Enter weight more than 0 kg.',

      cancel: 'Cancel',
      edit: 'Edit',
      save_apply: 'Save & Apply',
      max_selectable_date: 'Max. Selectable Date: ',
    },
    error_handling: {
      return_to_home: 'Return to Home',
      page_not_found: 'Page not found',
      link_not_found: 'The requested link is not found or has expired.',

      shipment_tracking_link_is_copied: 'Shipment tracking link is copied!',
      failed_to_copy_shipment_tracking_link:
        'Failed to copy shipment tracking link',
      close: 'Close',
    },
  },
};

